### ISSUE TITLE
Multi Text Translation per request

### ISSUE THREAD

**Issue by brenoepics** [brenoepics/at4j#17]

**Comment by genzarchitect** [comment]
I would love to work ont this. Can you give me some starting points?

**Comment by brenoepics** [comment]
@genzarchitect Thank you for your interest, the readme has how to install the library, 
for the translating multiple texts in a single request, [here is documentation from Microsoft.](https://learn.microsoft.com/en-us/azure/ai-services/translator/reference/v3-0-translate#request-body)

**Comment by genzarchitect** [comment]
@brenoepics Which java files need to be changed kindly mention ?
Could you please tell me how to run this repo so that i can test my changes weather it is running or not :)

**Comment by brenoepics** [comment]
multi translations per request done at https://github.com/brenoepics/at4j/commit/bf5f4e1267d18f310961c7033bc7f3ed3d77935f
but there`s still other endpoints from azure that accept multi per time todo if you want to.

probably need to change de AzureApiImpl and AzureApi.

For testing we have JUNIT5 and you can run https://github.com/brenoepics/Azure-Translator-Example
using local build as at4j dependency
